name: Download a file from anywhere

on:
  workflow_dispatch:    # lets you run it manually from GitHub web

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Download the target file
        run: |
          curl -L -o myfile.zip "https://download2389.mediafire.com/h4i7xeztfpagOABTj7wcth_-ZvlBP_woE59piwnRHSdxRIbWaZaNuZPqmBAKTuwHs-m8g0NxMhvFaZrv7uNvTxSrZAtKBxknoHkM3ys3K_QUmTndFuMN-Khywd8xDfR2gUdWh7xkZCpM1Ku17w-BbPyElw-DllpSp2Za0W8gE-9XyA/8jqsyckzz09bc2d/ramrqfix.zip"
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file
          path: myfile.zip
